version: '3.7'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - mynet

  worker:
    build: .
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - mynet

networks:
  mynet:
    driver: bridge
